

drop-chance:

  PLAYER: 0.01

  ALLAY: 0.01
  ARMADILLO: 0.01
  AXOLOTL:
    BLUE: 0.01
    CYAN: 0.01
    GOLD: 0.01
    LUCY: 0.01
    WILD: 0.01
  BAT: 0.01
  BEE: 0.01
  BLAZE: 0.01
  CAT:
    ALL_BLACK: 0.01
    BLACK: 0.01
    BRITISH_SHORTHAIR: 0.01
    CALICO: 0.01
    JELLIE: 0.01
    PERSIAN: 0.01
    RAGDOLL: 0.01
    RED: 0.01
    SIAMESE: 0.01
    TABBY: 0.01
    WHITE: 0.01
  CAVE_SPIDER: 0.01
  CHICKEN: 0.01
  COD: 0.01
  COW: 0.01
  #Creeper Heads are left out handled by the vanilla method of obtaining.
  DOLPHIN: 0.01
  DONKEY: 0.01
  DROWNED: 0.01
  ELDER_GUARDIAN: 0.01
  #Ender Dragon Heads are left out to be handled by the vanilla method of obtaining.
  ENDERMAN: 0.01
  ENDERMITE: 0.01
  EVOKER: 0.01
  FOX:
    RED: 0.01
    SNOW: 0.01
  FROG:
    COLD: 0.01
    TEMPERATE: 0.01
    WARM: 0.01
  GHAST: 0.01
  #Giants left out of plugin
  GLOW_SQUID: 0.01
  GOAT: 0.01
  GUARDIAN: 0.01
  HOGLIN: 0.01
  HORSE:
    BLACK: 0.01
    BROWN: 0.01
    CHESTNUT: 0.01
    CREAMY: 0.01
    DARK_BROWN: 0.01
    GRAY: 0.01
    WHITE: 0.01
  HUSK: 0.01
  ILLUSIONER: 0.01
  IRON_GOLEM: 0.01
  LLAMA:
    BROWN: 0.01
    CREAMY: 0.01
    GRAY: 0.01
    WHITE: 0.01
  MAGMA_CUBE: 0.01
  MULE: 0.01
  MUSHROOM_COW:
    BROWN: 0.01
    RED: 0.01
  OCELOT: 0.01
  PANDA:
    #Black panda represents all variants except "brown"
    BLACK: 0.01
    BROWN: 0.01
  PARROT:
    BLUE: 0.01
    CYAN: 0.01
    GRAY: 0.01
    GREEN: 0.01
    RED: 0.01
  PHANTOM: 0.01
  PIG: 0.01
  PIGLIN: 0.01
  PIGLIN_BRUTE: 0.01
  PILLAGER: 0.01
  POLAR_BEAR: 0.01
  PUFFERFISH: 0.01
  RABBIT:
    BLACK: 0.01
    BLACK_AND_WHITE: 0.01
    BROWN: 0.01
    GOLD: 0.01
    SALT_AND_PEPPER: 0.01
    THE_KILLER_BUNNY: 0.01
    WHITE: 0.01
    TOAST: 0.01
  RAVAGER: 0.01
  SALMON: 0.01
  SHEEP:
    BLACK: 0.01
    BLUE: 0.01
    BROWN: 0.01
    CYAN: 0.01
    GRAY: 0.01
    GREEN: 0.01
    LIGHT_BLUE: 0.01
    LIGHT_GRAY: 0.01
    LIME: 0.01
    MAGENTA: 0.01
    ORANGE: 0.01
    PINK: 0.01
    PURPLE: 0.01
    RED: 0.01
    WHITE: 0.01
    YELLOW: 0.01
    JEB_: 0.01
  SHULKER: 0.01
  SILVERFISH: 0.01
  #Skeleton Heads are left out handled by the vanilla method of obtaining.
  SKELETON_HORSE: 0.01
  SLIME: 0.01
  SNOWMAN: 0.01
  SPIDER: 0.01
  SQUID: 0.01
  STRAY: 0.01
  STRIDER:
    WARM: 0.01
    COLD: 0.01
  TADPOLE: 0.01
  TRADER_LLAMA:
    BROWN: 0.01
    CREAMY: 0.01
    GRAY: 0.01
    WHITE: 0.01
  TROPICAL_FISH: 0.01
  TURTLE: 0.01
  VEX: 0.01
  VILLAGER:
    DESERT: 0.01
    JUNGLE: 0.01
    PLAINS: 0.01
    SAVANNA: 0.01
    SNOW: 0.01
    SWAMP: 0.01
    TAIGA: 0.01
  VINDICATOR: 0.01
  WANDERING_TRADER: 0.01
  WARDEN: 0.01
  WITCH: 0.01
  WITHER: 0.01
  #Wither Skeleton Heads are left out handled by the vanilla method of obtaining.
  WOLF:
    ASHEN: 0.01
    BLACK: 0.01
    CHESTNUT: 0.01
    PALE: 0.01
    RUSTY: 0.01
    SNOWY: 0.01
    SPOTTED: 0.01
    STRIPED: 0.01
    WOODS: 0.01
  ZOGLIN: 0.01
  #Zombie Heads are left out handled by the vanilla method of obtaining.
  ZOMBIE_HORSE: 0.01
  ZOMBIE_VILLAGER: 0.01
  ZOMBIFIED_PIGLIN: 0.01