name: FeatherHeads
version: '${project.version}'
main: dev.zerek.featherheads.FeatherHeads
api-version: 1.19
authors: [ Zerek ]
description: Adds mob and player head drops when killed
commands:
  head:
    description: FeatherHeads command
